server:
  port: 8080
spring:
  datasource:
    # driver-class-name: org.h2.Driver
    # schema: classpath:db/schema-h2.sql
    # data: classpath:db/data-h2.sql
    # url: jdbc:h2:mem:test
    # username: root
    # password: test

   schema: classpath:db/schema-mysql.sql
   data: classpath:db/data-mysql.sql
   url: jdbc:mysql://${MYSQL_HOST}:3306/mysql?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
   username: root
   password: ${MYSQL_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

  jackson:
     serialization:
       WRITE_DATES_AS_TIMESTAMPS: false
     time-zone: UTC
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG